version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret 
      MYSQL_DATABASE: tsubuyaki
      MYSQL_USER: tsubuyaki
      MYSQL_PASSWORD: tokuronI 
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: {}
